name: esercizio_iglu_app
description: "App di gestione dei compiti"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.6
  auto_route: ^8.2.0
  flutter_svg: ^2.0.10+1
  mocktail: ^1.0.4


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  injectable_generator: ^2.1.3
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.11
  flutter_launcher_icons: ^0.13.1
  logger: ^2.3.0
  get_it: ^7.7.0
  injectable: ^2.4.2

flutter_launcher_icons:
  image_path: "assets/icon/icon.png"
  android: true
  ios: true
  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_background: "#0866FF"
  adaptive_icon_foreground: "assets/icon/icon-adaptive.png"

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/icon/icon.png
    - assets/icon/icon-background.png
    - assets/img/app-logo.svg